---
language: python
python: "2.7"

install: pip install ansible

script: ansible-playbook ansible/foreman.yml --syntax-check

- hosts: all
  tasks:
       - yum:
               name: ansible
       - yum:
               name: ansible-lint
       - yum:
               name: yamllint

- import_playbook: ansible-lint ./
- import_playbook: yammlint ./  
