---
language: python
python: "2.7"

install:
   - pip install ansible
   - pip install ansible-lint
   - pip install yamllint

script:
   - ansible-playbook ansible-lint ./
   - ansible-playbook yamllint ./
